import React, { useState, useRef, useEffect, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate, useLocation } from 'react-router-dom';
import { Send, UserCog, History, X, Trash2, ChevronRight, MessageCircle, Mic, Volume2, VolumeX, Sparkles, ArrowLeft, Share2 } from 'lucide-react';
import { askLocalAgent, detectMicroAnomalies, generateRandomDataSummary } from '../lib/localAgent';
import { analyzeBusinessQuery, generateBusinessResponse } from '../lib/gemini';
import { useShop } from '../context/ShopContext';
import { SpeechRecognition } from '@capacitor-community/speech-recognition';
import { Haptics, ImpactStyle } from '@capacitor/haptics';
import { Share } from '@capacitor/share';
import { Capacitor } from '@capacitor/core';
import toast from 'react-hot-toast';

// ─── Types ────────────────────────────────────────────────────────────────────
interface Message {
  id: string;
  text: string;
  isBot: boolean;
  time: string; // ISO string for JSON serialization
  isSparkle?: boolean; // If it was generated by Gemini
  isWelcome?: boolean; // If it's the first greet (to show live alerts)
}

interface ChatSession {
  id: string;
  title: string;
  messages: Message[];
  createdAt: string;
  updatedAt: string;
}

// ─── Storage helpers ──────────────────────────────────────────────────────────
const STORAGE_KEY = 'manager_chat_history';

function loadSessions(): ChatSession[] {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
  } catch { return []; }
}

function saveSessions(sessions: ChatSession[]) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(sessions.slice(0, 30))); // keep last 30
}

function makeWelcomeMessage(): Message {
  return {
    id: `b-welcome`,
    text: `🌟 **Assalam-o-Alaikum!**\n\nMain aapka **Business Manager** hoon.`,
    isBot: true,
    time: new Date().toISOString(),
    isWelcome: true // New flag for dynamic rendering
  };
}

// ─── Stress Meter Component ──────────────────────────────────────────────────
function StressMeter({ score }: { score: number }) {
  const isStressed = score < 60;
  const color = isStressed ? 'text-red-500' : 'text-[#00C853]';
  const bgColor = isStressed ? 'bg-red-500/10' : 'bg-[#00E676]/10';

  return (
    <div className={`flex items-center gap-3 p-3 rounded-2xl ${bgColor} border border-gray-100 dark:border-white/5`}>
       <div className="flex-1">
          <p className="text-[10px] font-black uppercase text-gray-400 mb-1">Biz-Stress Meter</p>
          <div className="h-1.5 w-full bg-gray-200 dark:bg-white/10 rounded-full overflow-hidden">
             <motion.div 
               initial={{ width: 0 }}
               animate={{ width: `${score}%` }}
               className={`h-full ${isStressed ? 'bg-red-500' : 'bg-[#00E676]'}`}
             />
          </div>
       </div>
       <div className={`text-sm font-black ${color}`}>{score < 60 ? 'HIGH' : 'SAFE'}</div>
    </div>
  );
}

// ─── Message Renderer ─────────────────────────────────────────────────────────
function renderBotMessage(text: string, isWelcome?: boolean, anomalies?: string[], onAction?: (a: string) => void) {
  const lines = (text || '').split('\n');
  return (
    <div className="space-y-3">
      {lines.map((line, i) => {
        const trimmed = (line || '').trim();
        if (!trimmed) return <div key={i} className="h-2" />;

        // [ACTION: Label] Detection
        const actionMatch = trimmed.match(/\[ACTION:\s*(.*?)\]/);
        if (actionMatch && actionMatch[1]) {
          return (
            <button 
              key={i}
              onClick={() => onAction?.(actionMatch[1])}
              className="w-full flex items-center justify-between p-4 bg-[#00E676]/5 hover:bg-[#00E676]/10 border border-[#00E676]/20 rounded-2xl transition-all group active:scale-[0.97] mb-1"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-[#00E676]/20 flex items-center justify-center text-[#00A846]">
                  <Sparkles size={18} strokeWidth={2.5} />
                </div>
                <span className="text-[14px] font-black text-[#00A846]">{actionMatch[1]}</span>
              </div>
              <ChevronRight size={18} className="text-[#00A846] opacity-50 group-hover:opacity-100 group-hover:translate-x-1 transition-all" />
            </button>
          );
        }

        if (/^─+$/.test(trimmed))
          return <hr key={i} className="border-gray-100 dark:border-white/5 my-2" />;

        const headingMatch = trimmed.match(/^(\p{Emoji_Presentation}|\p{Emoji}\uFE0F)\s*\*\*(.*?)\*\*$/u);
        if (headingMatch && headingMatch[2]) {
          return (
            <div key={i} className="flex items-center gap-2 pt-2 pb-1">
              <span className="text-xl drop-shadow-sm">{headingMatch[1] || ''}</span>
              <span className="text-[15px] font-black text-gray-900 dark:text-white tracking-tight">{headingMatch[2]}</span>
            </div>
          );
        }

        const amountMatch = trimmed.match(/^(.+?):\s*(-?)?(Rs\.[\d,]+|[\d,]+)(.*)$/);
        if (amountMatch && !trimmed.startsWith('•')) {
          const label = (amountMatch[1] || '').replace(/\*\*/g, '');
          const isNegative = trimmed.includes('-') || label.toLowerCase().includes('cogs') || label.toLowerCase().includes('expense');
          const isProfit = label.includes('Profit') || label.includes('profit') || label.includes('Munafa');
          const amountValue = (amountMatch[2] || '') + (amountMatch[3] || '');
          return (
            <div key={i} className={`flex items-center justify-between gap-4 p-4 rounded-2xl ${isProfit ? 'bg-[#00E676]/10 border border-[#00E676]/20' : 'bg-gray-50 dark:bg-white/5 border border-transparent'}`}>
              <span className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wider">{label}</span>
              <span className={`text-lg font-black tabular-nums ${isProfit ? 'text-[#00C853]' : isNegative ? 'text-red-500' : 'text-gray-900 dark:text-white'}`}>{amountValue}{amountMatch[4] || ''}</span>
            </div>
          );
        }

        if (trimmed.startsWith('•'))
          return (
            <div key={i} className="flex items-start gap-3 text-[14px] text-gray-700 dark:text-gray-300 px-1">
              <div className="w-1.5 h-1.5 rounded-full bg-[#00E676] mt-1.5 shrink-0" />
              <span className="leading-relaxed font-bold">{renderInlineBold(trimmed.slice(1).trim())}</span>
            </div>
          );

        const numMatch = trimmed.match(/^(\d+)\.\s+(.*)$/);
        if (numMatch && numMatch[2])
          return (
            <div key={i} className="flex items-start gap-3.5 text-[14px] text-gray-700 dark:text-gray-300">
              <span className="min-w-[24px] h-[24px] flex items-center justify-center bg-[#00E676]/10 text-[#00A846] dark:text-[#00E676] font-black text-[10px] rounded-lg mt-0.5">{numMatch[1]}</span>
              <span className="leading-relaxed flex-1 font-bold">{renderInlineBold(numMatch[2])}</span>
            </div>
          );

        return <p key={i} className="text-[14px] text-gray-700 dark:text-gray-300 font-bold leading-relaxed px-1">{renderInlineBold(trimmed)}</p>;
      })}
      
      {isWelcome && (
        <div className="pt-4 border-t border-gray-100 dark:border-white/5 mt-3 space-y-3">
           <StressMeter score={Math.min(100, Math.max(40, 80 + (anomalies?.length ? -anomalies.length * 10 : 10)))} />
           <p className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] px-1">Shop Insights</p>
          {anomalies && anomalies.length > 0 ? (
            <div className="bg-red-50 dark:bg-red-500/5 p-4 rounded-2xl border border-red-100 dark:border-red-500/10">
              <p className="text-[11px] font-black text-red-600 dark:text-red-400 uppercase flex items-center gap-2 mb-2">
                <span className="w-2 h-2 rounded-full bg-red-500 animate-pulse shadow-[0_0_8px_rgba(239,68,68,0.5)]" />
                Live Alert
              </p>
              <p className="text-[13px] font-bold text-gray-800 dark:text-gray-200 leading-snug">{anomalies[0].replace(/\*\*/g, '')}</p>
            </div>
          ) : (
             <div className="flex items-center gap-3 p-3 rounded-xl bg-green-50/50 dark:bg-[#00E676]/5 border border-green-100/50 dark:border-[#00E676]/10">
                <div className="w-2 h-2 rounded-full bg-[#00C853]" />
                <p className="text-[11px] font-black text-[#00A846] uppercase">Safe Analysis Mode Active</p>
             </div>
          )}
        </div>
      )}
    </div>
  );
}

function renderInlineBold(text: string): React.ReactNode {
  return text.split(/\*\*(.*?)\*\*/g).map((part, i) =>
    i % 2 === 1 ? <strong key={i} className="font-black text-gray-900 dark:text-white">{part}</strong> : part
  );
}

// ─── Quick Chips ──────────────────────────────────────────────────────────────
const QUICK_CHIPS = [
  "💰 Galle mein cash?",
  "📊 Aaj ki sale?",
  "🚨 Masail hal karein (Problems)",
  "⏳ Purani recovery?",
  "📈 Munafa barhaun?",
  "📦 Stock alert?",
];

// ─── History Panel ────────────────────────────────────────────────────────────
function HistoryPanel({
  sessions,
  onSelect,
  onDelete,
  onClose,
}: {
  sessions: ChatSession[];
  onSelect: (s: ChatSession) => void;
  onDelete: (id: string) => void;
  onClose: () => void;
}) {
  function formatDate(iso: string) {
    const d = new Date(iso);
    const today = new Date();
    const isToday = d.toDateString() === today.toDateString();
    if (isToday) return `Aaj ${d.toLocaleTimeString('ur-PK', { hour: '2-digit', minute: '2-digit' })}`;
    return d.toLocaleDateString('ur-PK', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });
  }

  return (
    <motion.div
      initial={{ x: '100%' }}
      animate={{ x: 0 }}
      exit={{ x: '100%' }}
      transition={{ type: 'spring', damping: 28, stiffness: 280 }}
      className="absolute inset-0 z-50 bg-slate-50 dark:bg-[#0A0A0A] flex flex-col"
    >
      {/* Header */}
      <div className="shrink-0 bg-gradient-to-br from-[#00E676] to-[#00A846] px-4 pt-12 pb-5">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-white/20 flex items-center justify-center">
              <History size={20} className="text-white" />
            </div>
            <div>
              <h2 className="text-lg font-black text-white">Chat History</h2>
              <p className="text-xs text-white/80">{sessions.length} guftagu saved hain</p>
            </div>
          </div>
          <button onClick={onClose} className="w-9 h-9 bg-white/20 rounded-full flex items-center justify-center active:scale-90">
            <X size={18} className="text-white" />
          </button>
        </div>
      </div>

      {/* List */}
      <div className="flex-1 overflow-y-auto p-4 space-y-2">
        {sessions.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full text-center px-6 pb-20">
            <div className="w-16 h-16 rounded-3xl bg-gray-100 dark:bg-white/5 flex items-center justify-center mb-4">
              <MessageCircle size={28} className="text-gray-300 dark:text-gray-600" />
            </div>
            <p className="text-gray-600 dark:text-gray-400 font-semibold text-base">Koi history nahi</p>
            <p className="text-gray-400 dark:text-gray-600 text-sm mt-1">Pehli guftagu karo — save ho jaayegi!</p>
          </div>
        ) : (
          sessions
            .slice()
            .sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime())
            .map((session) => (
              <div
                key={session.id}
                className="flex items-center gap-3 bg-white dark:bg-[#181818] border border-gray-100 dark:border-white/5 rounded-2xl px-4 py-3 shadow-sm active:scale-[0.98] transition-transform"
                onClick={() => onSelect(session)}
              >
                <div className="w-10 h-10 rounded-xl bg-[#00E676]/10 flex items-center justify-center shrink-0">
                  <UserCog size={18} className="text-[#00A846]" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-bold text-gray-900 dark:text-white truncate">{session.title}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{formatDate(session.updatedAt)} • {session.messages.length} messages</p>
                </div>
                <div className="flex items-center gap-1 shrink-0">
                  <button
                    onClick={(e) => { e.stopPropagation(); onDelete(session.id); }}
                    className="w-8 h-8 flex items-center justify-center rounded-full text-red-400 hover:bg-red-50 dark:hover:bg-red-500/10 active:scale-90"
                  >
                    <Trash2 size={15} />
                  </button>
                  <ChevronRight size={16} className="text-gray-300 dark:text-gray-600" />
                </div>
              </div>
            ))
        )}
      </div>
    </motion.div>
  );
}

// ─── Main Component ───────────────────────────────────────────────────────────
export const Manager: React.FC = () => {
  const { sales, expenses, udhaars, stock, contacts, profile } = useShop();

  // 🧪 Memoize shopData to prevent unnecessary re-calculates on every keystroke
  const shopData = useMemo(() => ({
    sales: Array.isArray(sales) ? sales : [],
    expenses: Array.isArray(expenses) ? expenses : [],
    udhaars: Array.isArray(udhaars) ? udhaars : [],
    stock: Array.isArray(stock) ? stock : [],
    contacts: Array.isArray(contacts) ? contacts : [],
    profile: profile || null,
  }), [sales, expenses, udhaars, stock, contacts, profile]);

  const location = useLocation();
  const navigate = useNavigate();

  const [sessions, setSessions] = useState<ChatSession[]>(loadSessions);
  const [currentSessionId, setCurrentSessionId] = useState<string>(() => `s-${Date.now()}`);
  
  // Memoized Live Vitals
  const allAnomalies = useMemo(() => {
    try {
      return detectMicroAnomalies(shopData).filter(x => x && !x.includes('Masha\'Allah'));
    } catch (e) {
      console.error("Anomaly detection failed", e);
      return [];
    }
  }, [shopData]);

  const [messages, setMessages] = useState<Message[]>([makeWelcomeMessage()]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [isListening, setIsListening] = useState(false);
  const [isSpeakerOn, setIsSpeakerOn] = useState(() => localStorage.getItem('manager_speaker') !== 'off');
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Auto-scroll
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isTyping]);

  // Auto-start voice if requested from Dashboard
  useEffect(() => {
    if ((location.state as any)?.autoStartVoice) {
      const timer = setTimeout(() => {
        startListening(true);
      }, 1200);
      return () => clearTimeout(timer);
    }
  }, []);

  // TTS Helper
  const speak = (text: string) => {
    if (!isSpeakerOn) return;
    window.speechSynthesis.cancel();
    // Clean text for speech (remove markdown, emoji symbols, and divider lines)
    const cleanText = text
       .replace(/\*\*(.*?)\*\*/g, '$1') // remove ** but keep text
       .replace(/─+/g, '')
       .replace(/•/g, '')
       .replace(/[🚀💰📊🚨⏳📈📦🌟🌟]/g, '') // remove common UI emojis for cleaner speech
       .replace(/\[ACTION:.*?\]/g, ''); // hide action buttons from speech

    const utterance = new SpeechSynthesisUtterance(cleanText);
    utterance.lang = 'ur-PK'; 
    utterance.pitch = 1.1; // Slightly more natural pitch
    utterance.rate = 1.0;
    window.speechSynthesis.speak(utterance);
  };

  const toggleSpeaker = () => {
    const newVal = !isSpeakerOn;
    setIsSpeakerOn(newVal);
    localStorage.setItem('manager_speaker', newVal ? 'on' : 'off');
    if (!newVal) window.speechSynthesis.cancel();
    Haptics.impact({ style: ImpactStyle.Light }).catch(() => {});
  };

  const handleShareSummary = async () => {
    if (messages.length <= 1) {
      toast.error('Pehle AI se kuch sawaal poochein!');
      return;
    }

    try {
      // Format messages into a nice summary
      let summary = `*Business Manager Report - ${shopData.profile?.name || 'KiryanaBook'}*\n`;
      summary += `📅 _${new Date().toLocaleDateString()}_\n\n`;
      
      // Get the last bot message primarily, or the whole conversation
      const lastBotMsg = [...messages].reverse().find(m => m.isBot);
      if (lastBotMsg) {
        summary += `*Summary:*\n${lastBotMsg.text.replace(/\*\*/g, '*').replace(/─+/g, '')}\n\n`;
      }
      
      summary += `_Hisaab-o-Kitaab, KiryanaBook Business Manager se_`;

      await Share.share({
        title: 'Business Manager Report',
        text: summary,
        dialogTitle: 'WhatsApp Summary Share',
      });
      
      Haptics.impact({ style: ImpactStyle.Medium }).catch(() => {});
    } catch (e) {
      console.error(e);
      toast.error('Share failed');
    }
  };

  const startListening = async (silent = false) => {
    // 🌐 WEB SPEECH API FALLBACK (Reliable for Browsers)
    const WebSpeech = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    
    if (WebSpeech && !Capacitor.isNativePlatform()) {
      try {
        const recognition = new WebSpeech();
        recognition.lang = 'ur-PK';
        recognition.interimResults = true;
        recognition.continuous = false;

        recognition.onstart = () => {
          setIsListening(true);
          Haptics.impact({ style: ImpactStyle.Heavy }).catch(() => {});
        };

        recognition.onresult = (event: any) => {
          const transcript = Array.from(event.results)
            .map((result: any) => result[0].transcript)
            .join('');
          setInput(transcript);
        };

        recognition.onend = () => {
          setIsListening(false);
          // Auto-send if we have enough text
          if (input.trim().length > 2) {
            handleSend();
          }
        };

        recognition.onerror = () => {
          setIsListening(false);
          if (!silent) toast.error('Mic access denied or error');
        };

        recognition.start();
        return;
      } catch (e) {
        console.error("Web Speech Error:", e);
      }
    }

    // 📱 NATIVE CAPACITOR IMPLEMENTATION
    try {
      const { available } = await SpeechRecognition.available();
      if (!available) {
        if (!silent) toast.error('Speech recognition not available');
        return;
      }

      await SpeechRecognition.requestPermissions();
      setIsListening(true);
      
      SpeechRecognition.start({
        language: 'ur-PK',
        partialResults: true,
        popup: false, // Don't show the native dialog if possible for cleaner integration
      });

      SpeechRecognition.addListener('partialResults', (data: any) => {
        if (data.matches && data.matches.length > 0) {
          setInput(data.matches[0]);
        }
      });
    } catch (e) {
      setIsListening(false);
      if (!silent) toast.error('Could not start mic');
    }
  };

  // Handle auto-send after voice input stops
  useEffect(() => {
    if (!Capacitor.isNativePlatform()) return;
    
    let stopHandle: any;
    const setupListener = async () => {
      stopHandle = await SpeechRecognition.addListener('listeningState', (state: any) => {
        if (state.status === 'stopped') {
          setIsListening(false);
          if (input.trim().length > 2) handleSend();
        }
      });
    };
    setupListener();

    return () => {
      if (stopHandle) stopHandle.remove();
      window.speechSynthesis.cancel();
    };
  }, [input]);

  // Auto-save session whenever messages change (if more than 1 message)
  useEffect(() => {
    if (messages.length <= 1) return;
    const firstUserMsg = messages.find(m => !m.isBot);
    const title = firstUserMsg ? firstUserMsg.text.slice(0, 40) : 'Nayi Guftagu';
    const now = new Date().toISOString();

    setSessions(prev => {
      const existing = prev.find(s => s.id === currentSessionId);
      let updated: ChatSession[];
      if (existing) {
        updated = prev.map(s => s.id === currentSessionId ? { ...s, messages, title, updatedAt: now } : s);
      } else {
        updated = [...prev, { id: currentSessionId, title, messages, createdAt: now, updatedAt: now }];
      }
      saveSessions(updated);
      return updated;
    });
  }, [messages, currentSessionId]);

  const startNewChat = () => {
    setCurrentSessionId(`s-${Date.now()}`);
    setMessages([makeWelcomeMessage()]);
    setInput('');
    setShowHistory(false);
  };

  const handleSend = async (text: string = input) => {
    if (!text.trim()) return;
    const userMsg: Message = { id: `u-${Date.now()}`, text: text.trim(), isBot: false, time: new Date().toISOString() };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setIsTyping(true);

    // 1. Try Gemini AI (Smart Brain)
    let finalResponse = '';
    let isSmart = false;
    
    try {
      const dataSummary = generateRandomDataSummary(shopData);
      const intent = await analyzeBusinessQuery(text.trim());
      
      // If Gemini gives a valid intent or response, use it
      if (intent && intent !== 'HEALTH_CHECK' && intent !== 'UNKNOWN') {
        const aiResponse = await generateBusinessResponse(text.trim(), dataSummary, intent);
        if (aiResponse && !aiResponse.includes('Error:') && !aiResponse.includes('API Key')) {
          finalResponse = aiResponse;
          isSmart = true;
        }
      }
    } catch (e) {
      console.error("Gemini AI failed, falling back to local:", e);
    }

    // 2. Fallback to Local Agent (Offline Brain)
    if (!finalResponse) {
      finalResponse = askLocalAgent(text.trim(), shopData);
      isSmart = finalResponse.includes('💡') || finalResponse.includes('⚠️');
    }

    setIsTyping(false);
    setMessages(prev => [...prev, { 
      id: `b-${Date.now()}`, 
      text: finalResponse, 
      isBot: true, 
      time: new Date().toISOString(),
      isSparkle: isSmart
    }]);
    speak(finalResponse);
  };

  const handleSelectSession = (session: ChatSession) => {
    setCurrentSessionId(session.id);
    setMessages(session.messages);
    setShowHistory(false);
  };

  const handleDeleteSession = (id: string) => {
    setSessions(prev => {
      const updated = prev.filter(s => s.id !== id);
      saveSessions(updated);
      return updated;
    });
    if (id === currentSessionId) startNewChat();
  };

  return (
    <div className="w-full max-w-md mx-auto h-[calc(100vh-90px)] flex flex-col bg-[#F9F9FB] dark:bg-[#0A0A0A] relative overflow-hidden">

      {/* ── Header ─────────────────────────────────────────────────────────── */}
      <div className="shrink-0 bg-gradient-to-br from-[#00E676] to-[#00A846] px-5 pt-[calc(3rem+env(safe-area-inset-top,0px))] pb-5 shadow-[0_10px_30px_rgba(0,168,70,0.15)] rounded-b-[2.8rem] relative overflow-hidden">
        {/* Glow effect */}
        <div className="absolute top-0 right-0 w-32 h-32 bg-white/20 rounded-full blur-3xl -mr-10 -mt-10" />
        <div className="absolute bottom-0 left-0 w-24 h-24 bg-white/10 rounded-full blur-2xl -ml-5 -mb-5" />
        
        <div className="flex items-center justify-between relative z-10">
          <div className="flex items-center gap-4">
            <button onClick={() => navigate(-1)} className="w-9 h-9 rounded-2xl bg-white/10 flex items-center justify-center text-white active:scale-90 transition-all backdrop-blur-md border border-white/20">
                <ArrowLeft size={18} strokeWidth={3} />
            </button>
            <div className="flex-1">
              <h1 className="text-[18px] font-black text-white leading-none mb-1 tracking-tight">Business Manager</h1>
              <div className="flex items-center gap-1.5">
                <div className="w-1.5 h-1.5 rounded-full bg-[#4BFF94] animate-pulse shadow-[0_0_8px_#4BFF94]" />
                <p className="text-[9px] font-black text-white/80 uppercase tracking-[0.2em]">Strategy Advisor</p>
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
               onClick={handleShareSummary}
               className="w-10 h-10 bg-white/15 rounded-[1.2rem] flex items-center justify-center text-white active:scale-90 transition-all border border-white/10"
               title="Share Report"
            >
              <Share2 size={17} strokeWidth={2.5} />
            </button>
            <button
               onClick={() => setShowHistory(true)}
               className="w-10 h-10 bg-white/15 rounded-[1.2rem] flex items-center justify-center text-white active:scale-90 transition-all border border-white/10"
               title="History"
            >
              <History size={17} strokeWidth={2.5} />
            </button>
            <button
              onClick={toggleSpeaker}
              className={`w-10 h-10 ${isSpeakerOn ? 'bg-white/15' : 'bg-red-500/30'} rounded-[1.2rem] flex items-center justify-center active:scale-90 transition-all border border-white/10`}
            >
              {isSpeakerOn ? <Volume2 size={17} strokeWidth={2.5} className="text-white" /> : <VolumeX size={17} strokeWidth={2.5} className="text-white" />}
            </button>
          </div>
        </div>
      </div>

      {/* ── Chat Messages ── */}
      <div className="flex-1 overflow-y-auto px-4 py-6 space-y-6">
        {(messages || []).map((msg) => (
          <motion.div
            key={msg?.id || Math.random()}
            initial={{ opacity: 0, y: 15, scale: 0.98 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            transition={{ duration: 0.25 }}
            className={`flex items-start gap-3 ${msg?.isBot ? 'justify-start pr-8' : 'justify-end pl-8'}`}
          >
            {msg?.isBot && (
              <div className="w-9 h-9 rounded-[1.1rem] bg-white dark:bg-[#1A1A1A] flex items-center justify-center shrink-0 shadow-[0_4px_12px_rgba(0,0,0,0.05)] border border-gray-100 dark:border-white/5 mt-0.5">
                <UserCog size={18} className="text-[#00C853]" strokeWidth={2.5} />
              </div>
            )}
            <div className={`max-w-full rounded-[1.8rem] px-5 py-4 relative shadow-[0_8px_25px_rgba(0,0,0,0.03)] ${msg?.isBot
              ? 'bg-white dark:bg-[#141414] border border-gray-100 dark:border-white/5 rounded-tl-none'
              : 'bg-[#00E676] text-[#0A0A0A] rounded-tr-none'}`}
            >
              {msg?.isSparkle && (
                <div className="absolute -top-2.5 -left-2.5 w-7 h-7 bg-gradient-to-br from-indigo-500 to-indigo-700 rounded-xl flex items-center justify-center shadow-lg transform rotate-[-12deg] border-2 border-white dark:border-[#141414]">
                  <Sparkles size={12} className="text-white" />
                </div>
              )}
              {msg?.isBot 
                ? renderBotMessage(msg?.text || '', msg?.isWelcome, allAnomalies, (action) => handleSend(`${action} ke baray mein batao`)) 
                : <p className="text-[15px] font-black tracking-tight leading-relaxed">{(msg?.text || '')}</p>
              }
              <div className={`flex items-center gap-1 mt-2.5 ${msg?.isBot ? 'justify-start' : 'justify-end'}`}>
                <span className={`text-[9px] font-black uppercase tracking-widest ${msg?.isBot ? 'text-gray-400' : 'text-black/40'}`}>
                   {msg?.time ? new Date(msg.time).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }) : '--:--'}
                </span>
              </div>
            </div>
          </motion.div>
        ))}

        {isTyping && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex items-start gap-3">
             <div className="w-9 h-9 rounded-[1.1rem] bg-white dark:bg-[#1A1A1A] flex items-center justify-center shrink-0 shadow-sm border border-gray-100 dark:border-white/5">
                <UserCog size={18} className="text-[#00C853]" />
              </div>
            <div className="bg-white dark:bg-[#141414] border border-gray-100 dark:border-white/5 rounded-2xl rounded-tl-none px-5 py-4 shadow-sm">
              <div className="flex gap-1.5 items-center h-5">
                {[0, 1, 2].map(i => (
                  <motion.span key={i} className="w-2 h-2 bg-[#00E676] rounded-full"
                    animate={{ scale: [1, 1.5, 1], opacity: [0.4, 1, 0.4] }}
                    transition={{ duration: 0.8, repeat: Infinity, delay: i * 0.2 }}
                  />
                ))}
              </div>
            </div>
          </motion.div>
        )}

        {messages.length === 1 && !isTyping && (
          <div className="pt-2 px-1">
            <p className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] mb-3 ml-2">Quick Commands</p>
            <div className="flex flex-wrap gap-2">
              {QUICK_CHIPS.map((chip, i) => (
                <button key={i} onClick={() => handleSend(chip)}
                  className="bg-white dark:bg-[#141414] border border-gray-100 dark:border-white/5 text-gray-800 dark:text-gray-200 text-[13px] font-black py-3 px-5 rounded-[1.3rem] shadow-sm transform hover:translate-y-[-2px] active:scale-95 transition-all">
                  {chip}
                </button>
              ))}
            </div>
          </div>
        )}

        <div ref={messagesEndRef} className="h-6" />
      </div>

      {/* ── Input ──────────────────────────────────────────────────────────── */}
      <div className="shrink-0 px-5 py-3 bg-white dark:bg-[#0A0A0A] border-t border-gray-100 dark:border-white/5 shadow-[0_-15px_40px_rgba(0,0,0,0.04)] z-50">
        <div className="flex gap-3 items-center">
          <div className="relative flex-1">
             <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleSend()}
              placeholder="Manager se poochein..."
              className="w-full bg-[#F5F7F9] dark:bg-[#141414] text-gray-900 dark:text-white rounded-[1.8rem] py-5 pl-7 pr-16 font-black text-sm placeholder-gray-400/80 focus:outline-none focus:ring-4 focus:ring-[#00E676]/15 border-2 border-transparent focus:border-[#00E676]/30 transition-all shadow-inner"
            />
            <button 
              onClick={() => startListening()}
              className={`absolute right-2 top-1/2 -translate-y-1/2 w-12 h-12 rounded-[1.2rem] flex items-center justify-center transition-all ${
                isListening ? 'bg-red-500 text-white shadow-[0_0_20px_rgba(239,68,68,0.4)]' : 'text-gray-400 hover:text-[#00E676] bg-transparent'
              }`}
            >
              {isListening ? (
                <div className="relative">
                  <Mic size={22} strokeWidth={2.5} />
                  <motion.span className="absolute -inset-3 bg-red-500/20 rounded-full" animate={{ scale: [1, 1.6, 1], opacity: [1, 0, 1] }} transition={{ repeat: Infinity, duration: 1.2 }} />
                </div>
              ) : <Mic size={22} strokeWidth={2.5} />}
            </button>
          </div>

          <button onClick={() => handleSend()} disabled={!input.trim()}
            className="w-16 h-16 rounded-[1.8rem] bg-[#00E676] text-[#0A0A0A] flex items-center justify-center disabled:opacity-20 disabled:grayscale active:scale-90 transition-all shadow-[0_12px_28px_rgba(0,230,118,0.25)] shrink-0 group">
            <Send size={24} strokeWidth={4} className="translate-x-[2px] transform transition-transform group-hover:translate-x-[4px] group-hover:-translate-y-[2px]" />
          </button>
        </div>
      </div>

      {/* ── History Panel ───────────────────────────────────────────────────── */}
      <AnimatePresence>
        {showHistory && (
          <HistoryPanel
            sessions={sessions}
            onSelect={handleSelectSession}
            onDelete={handleDeleteSession}
            onClose={() => setShowHistory(false)}
          />
        )}
      </AnimatePresence>
    </div>
  );
};
