import React, { useState, useRef, useEffect, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useLocation } from 'react-router-dom';
import { Send, UserCog, History, X, Trash2, ChevronRight, MessageCircle, Mic, Volume2, VolumeX, Sparkles } from 'lucide-react';
import { askLocalAgent, detectMicroAnomalies } from '../lib/localAgent';
import { useShop } from '../context/ShopContext';
import { SpeechRecognition } from '@capacitor-community/speech-recognition';
import { Haptics, ImpactStyle } from '@capacitor/haptics';
import { Share } from '@capacitor/share';
import toast from 'react-hot-toast';

// ─── Types ────────────────────────────────────────────────────────────────────
interface Message {
  id: string;
  text: string;
  isBot: boolean;
  time: string; // ISO string for JSON serialization
  isSparkle?: boolean; // If it was generated by Gemini
  isWelcome?: boolean; // If it's the first greet (to show live alerts)
}

interface ChatSession {
  id: string;
  title: string;
  messages: Message[];
  createdAt: string;
  updatedAt: string;
}

// ─── Storage helpers ──────────────────────────────────────────────────────────
const STORAGE_KEY = 'manager_chat_history';

function loadSessions(): ChatSession[] {
  try {
    return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
  } catch { return []; }
}

function saveSessions(sessions: ChatSession[]) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(sessions.slice(0, 30))); // keep last 30
}

function makeWelcomeMessage(): Message {
  return {
    id: `b-welcome`,
    text: `🌟 **Assalam-o-Alaikum!**\n\nMain aapka **AI Munshi** hoon.`,
    isBot: true,
    time: new Date().toISOString(),
    isWelcome: true // New flag for dynamic rendering
  };
}

// ─── Stress Meter Component ──────────────────────────────────────────────────
function StressMeter({ score }: { score: number }) {
  const isStressed = score < 60;
  const color = isStressed ? 'text-red-500' : 'text-[#00C853]';
  const bgColor = isStressed ? 'bg-red-500/10' : 'bg-[#00E676]/10';

  return (
    <div className={`flex items-center gap-3 p-3 rounded-2xl ${bgColor} border border-gray-100 dark:border-white/5`}>
       <div className="flex-1">
          <p className="text-[10px] font-black uppercase text-gray-400 mb-1">Biz-Stress Meter</p>
          <div className="h-1.5 w-full bg-gray-200 dark:bg-white/10 rounded-full overflow-hidden">
             <motion.div 
               initial={{ width: 0 }}
               animate={{ width: `${score}%` }}
               className={`h-full ${isStressed ? 'bg-red-500' : 'bg-[#00E676]'}`}
             />
          </div>
       </div>
       <div className={`text-sm font-black ${color}`}>{score < 60 ? 'HIGH' : 'SAFE'}</div>
    </div>
  );
}

// ─── Message Renderer ─────────────────────────────────────────────────────────
function renderBotMessage(text: string, isWelcome?: boolean, anomalies?: string[], onAction?: (a: string) => void) {
  const lines = text.split('\n');
  return (
    <div className="space-y-2">
      {lines.map((line, i) => {
        const trimmed = line.trim();
        if (!trimmed) return <div key={i} className="h-1" />;

        // [ACTION: Label] Detection
        const actionMatch = trimmed.match(/\[ACTION:\s*(.*?)\]/);
        if (actionMatch) {
          return (
            <button 
              key={i}
              onClick={() => onAction?.(actionMatch[1])}
              className="w-full flex items-center justify-between p-3 bg-[#00E676]/10 hover:bg-[#00E676]/20 border border-[#00E676]/30 rounded-xl transition-all group active:scale-95 mb-1"
            >
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-lg bg-[#00E676] flex items-center justify-center text-[#0A0A0A]">
                  <Sparkles size={16} />
                </div>
                <span className="text-sm font-bold text-[#00A846]">{actionMatch[1]}</span>
              </div>
              <ChevronRight size={16} className="text-[#00A846] group-hover:translate-x-1 transition-transform" />
            </button>
          );
        }

        if (/^─+$/.test(trimmed))
          return <hr key={i} className="border-gray-200 dark:border-white/10 my-1" />;

        const headingMatch = trimmed.match(/^(\p{Emoji_Presentation}|\p{Emoji}\uFE0F)\s*\*\*(.*?)\*\*$/u);
        if (headingMatch)
          return (
            <div key={i} className="flex items-center gap-2 pb-1">
              <span className="text-xl">{headingMatch[1]}</span>
              <span className="text-base font-black text-gray-900 dark:text-white leading-snug">{headingMatch[2]}</span>
            </div>
          );

        const amountMatch = trimmed.match(/^(.+?):\s*(-?)?(Rs\.[\d,]+|[\d,]+)(.*)$/);
        if (amountMatch && !trimmed.startsWith('•')) {
          const label = amountMatch[1].replace(/\*\*/g, '');
          const isNegative = trimmed.includes('-') || label.toLowerCase().includes('cogs') || label.toLowerCase().includes('expense');
          const isProfit = label.includes('Profit') || label.includes('profit') || label.includes('Munafa');
          const amount = (amountMatch[2] || '') + amountMatch[3];
          return (
            <div key={i} className={`flex items-center justify-between gap-3 py-2 px-3 rounded-xl ${isProfit ? 'bg-[#00E676]/10 border border-[#00E676]/20' : 'bg-gray-50 dark:bg-white/5'}`}>
              <span className="text-sm font-semibold text-gray-500 dark:text-gray-400">{label}</span>
              <span className={`text-lg font-black tabular-nums ${isProfit ? 'text-[#00C853]' : isNegative ? 'text-red-500' : 'text-gray-900 dark:text-white'}`}>{amount}{amountMatch[4]}</span>
            </div>
          );
        }

        if (trimmed.startsWith('•'))
          return (
            <div key={i} className="flex items-start gap-2 text-sm text-gray-700 dark:text-gray-300">
              <span className="mt-1 text-[#00C853] font-black text-xs">●</span>
              <span className="leading-relaxed">{renderInlineBold(trimmed.slice(1).trim())}</span>
            </div>
          );

        const numMatch = trimmed.match(/^(\d+)\.\s+(.*)$/);
        if (numMatch)
          return (
            <div key={i} className="flex items-start gap-2.5 text-sm text-gray-700 dark:text-gray-300">
              <span className="min-w-[22px] h-[22px] flex items-center justify-center bg-[#00E676]/20 text-[#00A846] dark:text-[#00E676] font-black text-xs rounded-full mt-0.5">{numMatch[1]}</span>
              <span className="leading-relaxed flex-1">{renderInlineBold(numMatch[2])}</span>
            </div>
          );

        return <p key={i} className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">{renderInlineBold(trimmed)}</p>;
      })}
      
      {isWelcome && (
        <div className="pt-2 border-t border-gray-100 dark:border-white/5 mt-2">
          {anomalies && anomalies.length > 0 ? (
            <div className="bg-red-50 dark:bg-red-500/10 p-2.5 rounded-xl border border-red-100 dark:border-red-500/20">
              <p className="text-[11px] font-black text-red-600 dark:text-red-400 uppercase flex items-center gap-1.5 mb-1">
                <span className="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse" />
                Live Alert
              </p>
              <p className="text-xs font-bold text-gray-800 dark:text-gray-200">{anomalies[0].replace(/\*\*/g, '')}</p>
            </div>
          ) : (
            <div className="grid grid-cols-2 gap-2">
               <div className="text-[11px] font-bold text-gray-500">• 📊 Hisaab</div>
               <div className="text-[11px] font-bold text-gray-500">• 🚨 Masail</div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function renderInlineBold(text: string): React.ReactNode {
  return text.split(/\*\*(.*?)\*\*/g).map((part, i) =>
    i % 2 === 1 ? <strong key={i} className="font-black text-gray-900 dark:text-white">{part}</strong> : part
  );
}

// ─── Quick Chips ──────────────────────────────────────────────────────────────
const QUICK_CHIPS = [
  "💰 Galle mein cash?",
  "📊 Aaj ki sale?",
  "🚨 Masail hal karein (Problems)",
  "⏳ Purani recovery?",
  "📈 Munafa barhaun?",
  "📦 Stock alert?",
];

// ─── History Panel ────────────────────────────────────────────────────────────
function HistoryPanel({
  sessions,
  onSelect,
  onDelete,
  onClose,
}: {
  sessions: ChatSession[];
  onSelect: (s: ChatSession) => void;
  onDelete: (id: string) => void;
  onClose: () => void;
}) {
  function formatDate(iso: string) {
    const d = new Date(iso);
    const today = new Date();
    const isToday = d.toDateString() === today.toDateString();
    if (isToday) return `Aaj ${d.toLocaleTimeString('ur-PK', { hour: '2-digit', minute: '2-digit' })}`;
    return d.toLocaleDateString('ur-PK', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });
  }

  return (
    <motion.div
      initial={{ x: '100%' }}
      animate={{ x: 0 }}
      exit={{ x: '100%' }}
      transition={{ type: 'spring', damping: 28, stiffness: 280 }}
      className="absolute inset-0 z-50 bg-slate-50 dark:bg-[#0A0A0A] flex flex-col"
    >
      {/* Header */}
      <div className="shrink-0 bg-gradient-to-br from-[#00E676] to-[#00A846] px-4 pt-12 pb-5">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-white/20 flex items-center justify-center">
              <History size={20} className="text-white" />
            </div>
            <div>
              <h2 className="text-lg font-black text-white">Chat History</h2>
              <p className="text-xs text-white/80">{sessions.length} guftagu saved hain</p>
            </div>
          </div>
          <button onClick={onClose} className="w-9 h-9 bg-white/20 rounded-full flex items-center justify-center active:scale-90">
            <X size={18} className="text-white" />
          </button>
        </div>
      </div>

      {/* List */}
      <div className="flex-1 overflow-y-auto p-4 space-y-2">
        {sessions.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full text-center px-6 pb-20">
            <div className="w-16 h-16 rounded-3xl bg-gray-100 dark:bg-white/5 flex items-center justify-center mb-4">
              <MessageCircle size={28} className="text-gray-300 dark:text-gray-600" />
            </div>
            <p className="text-gray-600 dark:text-gray-400 font-semibold text-base">Koi history nahi</p>
            <p className="text-gray-400 dark:text-gray-600 text-sm mt-1">Pehli guftagu karo — save ho jaayegi!</p>
          </div>
        ) : (
          sessions
            .slice()
            .sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime())
            .map((session) => (
              <div
                key={session.id}
                className="flex items-center gap-3 bg-white dark:bg-[#181818] border border-gray-100 dark:border-white/5 rounded-2xl px-4 py-3 shadow-sm active:scale-[0.98] transition-transform"
                onClick={() => onSelect(session)}
              >
                <div className="w-10 h-10 rounded-xl bg-[#00E676]/10 flex items-center justify-center shrink-0">
                  <UserCog size={18} className="text-[#00A846]" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-bold text-gray-900 dark:text-white truncate">{session.title}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{formatDate(session.updatedAt)} • {session.messages.length} messages</p>
                </div>
                <div className="flex items-center gap-1 shrink-0">
                  <button
                    onClick={(e) => { e.stopPropagation(); onDelete(session.id); }}
                    className="w-8 h-8 flex items-center justify-center rounded-full text-red-400 hover:bg-red-50 dark:hover:bg-red-500/10 active:scale-90"
                  >
                    <Trash2 size={15} />
                  </button>
                  <ChevronRight size={16} className="text-gray-300 dark:text-gray-600" />
                </div>
              </div>
            ))
        )}
      </div>
    </motion.div>
  );
}

// ─── Main Component ───────────────────────────────────────────────────────────
export const Manager: React.FC = () => {
  const { sales, expenses, udhaars, stock, contacts, profile } = useShop();
  const shopData = { sales, expenses, udhaars, stock, contacts, profile };
  const location = useLocation();


  const [sessions, setSessions] = useState<ChatSession[]>(loadSessions);
  const [currentSessionId, setCurrentSessionId] = useState<string>(() => `s-${Date.now()}`);
  
  // 🧪 Memoized Live Vitals (Phase 13 & 14)
  const allAnomalies = useMemo(() => 
    detectMicroAnomalies(shopData).filter(x => x && !x.includes('Masha\'Allah')),
    [shopData]
  );
  
  const activeAlerts = useMemo(() => allAnomalies.slice(0, 2), [allAnomalies]);
  const healthScore = useMemo(() => 
    Math.min(100, Math.max(40, 80 + (sales.length > 5 ? 10 : 0) - (udhaars.length > 10 ? 5 : 0))),
    [sales.length, udhaars.length]
  );
  
  const liquidityStatus = useMemo(() => 
    (sales.reduce((a,b)=>a+b.total,0) - expenses.reduce((a,b)=>a+b.amount,0)) > 0 ? 'Surplus' : 'Deficit',
    [sales, expenses]
  );

  const [messages, setMessages] = useState<Message[]>([makeWelcomeMessage()]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [isListening, setIsListening] = useState(false);
  const [isSpeakerOn, setIsSpeakerOn] = useState(() => localStorage.getItem('manager_speaker') !== 'off');
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Auto-scroll
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isTyping]);

  // Auto-start voice if requested from Dashboard
  useEffect(() => {
    if ((location.state as any)?.autoStartVoice) {
      setTimeout(() => {
        startListening();
      }, 500);
    }
  }, []);

  // TTS Helper
  const speak = (text: string) => {
    if (!isSpeakerOn) return;
    window.speechSynthesis.cancel();
    // Clean text for speech (remove markdown)
    const cleanText = text.replace(/\*\*/g, '').replace(/─+/g, '').replace(/•/g, '').replace(/#/g, '');
    const utterance = new SpeechSynthesisUtterance(cleanText);
    utterance.lang = 'ur-PK'; // Urdu fallback
    utterance.rate = 1.0;
    window.speechSynthesis.speak(utterance);
  };

  const toggleSpeaker = () => {
    const newVal = !isSpeakerOn;
    setIsSpeakerOn(newVal);
    localStorage.setItem('manager_speaker', newVal ? 'on' : 'off');
    if (!newVal) window.speechSynthesis.cancel();
    Haptics.impact({ style: ImpactStyle.Light }).catch(() => {});
  };

  const handleShareSummary = async () => {
    if (messages.length <= 1) {
      toast.error('Pehle AI se kuch sawaal poochein!');
      return;
    }

    try {
      // Format messages into a nice summary
      let summary = `*AI Munshi Report - ${shopData.profile?.name || 'KiryanaBook'}*\n`;
      summary += `📅 _${new Date().toLocaleDateString()}_\n\n`;
      
      // Get the last bot message primarily, or the whole conversation
      const lastBotMsg = [...messages].reverse().find(m => m.isBot);
      if (lastBotMsg) {
        summary += `*Summary:*\n${lastBotMsg.text.replace(/\*\*/g, '*').replace(/─+/g, '')}\n\n`;
      }
      
      summary += `_Hisaab-o-Kitaab, KiryanaBook AI Munshi se_`;

      await Share.share({
        title: 'AI Munshi Report',
        text: summary,
        dialogTitle: 'WhatsApp Summary Share',
      });
      
      Haptics.impact({ style: ImpactStyle.Medium }).catch(() => {});
    } catch (e) {
      console.error(e);
      toast.error('Share failed');
    }
  };

  const startListening = async () => {
    try {
      const { available } = await SpeechRecognition.available();
      if (!available) {
        toast.error('Speech recognition not available');
        return;
      }

      await SpeechRecognition.requestPermissions();
      
      Haptics.impact({ style: ImpactStyle.Heavy }).catch(() => {});
      setIsListening(true);
      
      SpeechRecognition.start({
        language: 'ur-PK',
        partialResults: true,
        popup: true,
      });

      SpeechRecognition.addListener('partialResults', (data) => {
        if (data.matches && data.matches.length > 0) {
          setInput(data.matches[0]);
        }
      });

      // Simple timeout/auto-stop simulation for better UX if needed
      // but 'popup: true' handles it on most Android devices.
    } catch (e) {
      console.error(e);
      setIsListening(false);
      toast.error('Could not start mic');
    }
  };

  // Add listener for speech end
  useEffect(() => {
    let handle: any;
    
    const setupListener = async () => {
      handle = await SpeechRecognition.addListener('listeningState', (state) => {
        if (state.status === 'stopped') {
          setIsListening(false);
        }
      });
    };

    setupListener();

    return () => {
      if (handle) handle.remove();
      window.speechSynthesis.cancel();
    };
  }, []);

  // Auto-save session whenever messages change (if more than 1 message)
  useEffect(() => {
    if (messages.length <= 1) return;
    const firstUserMsg = messages.find(m => !m.isBot);
    const title = firstUserMsg ? firstUserMsg.text.slice(0, 40) : 'Nayi Guftagu';
    const now = new Date().toISOString();

    setSessions(prev => {
      const existing = prev.find(s => s.id === currentSessionId);
      let updated: ChatSession[];
      if (existing) {
        updated = prev.map(s => s.id === currentSessionId ? { ...s, messages, title, updatedAt: now } : s);
      } else {
        updated = [...prev, { id: currentSessionId, title, messages, createdAt: now, updatedAt: now }];
      }
      saveSessions(updated);
      return updated;
    });
  }, [messages, currentSessionId]);

  const startNewChat = () => {
    setCurrentSessionId(`s-${Date.now()}`);
    setMessages([makeWelcomeMessage()]);
    setInput('');
    setShowHistory(false);
  };

  const handleSend = async (text: string = input) => {
    if (!text.trim()) return;
    const userMsg: Message = { id: `u-${Date.now()}`, text: text.trim(), isBot: false, time: new Date().toISOString() };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setIsTyping(true);

    // 1. Full Offline Agent (No APIs)
    await new Promise(r => setTimeout(r, 700)); // Artificial thinking delay for UX
    const finalResponse = askLocalAgent(text.trim(), shopData);
    
    // Flag if it's considered "smart" (e.g. contains a generated tip instead of raw data)
    let isSmart = finalResponse.includes('💡') || finalResponse.includes('⚠️');

    setIsTyping(false);
    setMessages(prev => [...prev, { 
      id: `b-${Date.now()}`, 
      text: finalResponse, 
      isBot: true, 
      time: new Date().toISOString(),
      isSparkle: isSmart // For custom UI indicator
    }]);
    speak(finalResponse);
  };

  const handleSelectSession = (session: ChatSession) => {
    setCurrentSessionId(session.id);
    setMessages(session.messages);
    setShowHistory(false);
  };

  const handleDeleteSession = (id: string) => {
    setSessions(prev => {
      const updated = prev.filter(s => s.id !== id);
      saveSessions(updated);
      return updated;
    });
    if (id === currentSessionId) startNewChat();
  };

  return (
    <div className="fixed inset-0 w-full max-w-md mx-auto pb-[calc(90px+env(safe-area-inset-bottom,0px))] flex flex-col bg-slate-50 dark:bg-[#0A0A0A] overflow-hidden z-[40]">

      {/* ── Header ─────────────────────────────────────────────────────────── */}
      <div className="shrink-0 bg-gradient-to-br from-[#00E676] to-[#00A846] px-4 pt-12 pb-5 shadow-lg">
        <div className="flex items-center gap-3">
          <div className="w-11 h-11 rounded-2xl bg-white/20 flex items-center justify-center">
            <UserCog size={22} className="text-white" />
          </div>
          <div className="flex-1">
            <h1 className="text-xl font-black text-white" style={{ fontFamily: "'Outfit', sans-serif" }}>Shop Manager</h1>
            <p className="text-xs font-semibold text-white/80">Aapka Munshi · CA · Advisor</p>
          </div>
          {/* New Chat */}
          <button
            onClick={startNewChat}
            className="bg-white/20 text-white text-xs font-bold px-3 py-1.5 rounded-full active:scale-90 transition-transform border border-white/20"
          >
            + Naya Chat
          </button>
          {/* WhatsApp Share */}
          <button
            onClick={handleShareSummary}
            className="w-10 h-10 bg-[#25D366]/20 rounded-full flex items-center justify-center active:scale-90 transition-all border border-[#25D366]/30"
            title="WhatsApp Summary"
          >
            <MessageCircle size={18} className="text-[#25D366]" />
          </button>

          {/* Speaker Toggle */}
          <button
            onClick={toggleSpeaker}
            className={`w-10 h-10 ${isSpeakerOn ? 'bg-white/20' : 'bg-red-500/30'} rounded-full flex items-center justify-center active:scale-90 transition-all border border-white/20`}
          >
            {isSpeakerOn ? <Volume2 size={18} className="text-white" /> : <VolumeX size={18} className="text-white" />}
          </button>
          
          {/* History */}
          <button
            onClick={() => setShowHistory(true)}
            className="relative w-10 h-10 bg-white/20 rounded-full flex items-center justify-center active:scale-90 transition-transform border border-white/20"
          >
            <History size={18} className="text-white" />
            {sessions.length > 0 && (
              <span className="absolute -top-1 -right-1 w-4 h-4 bg-white text-[#00A846] text-[9px] font-black rounded-full flex items-center justify-center">
                {sessions.length > 9 ? '9+' : sessions.length}
              </span>
            )}
          </button>
        </div>
      </div>

      {/* ── Messages ───────────────────────────────────────────────────────── */}
      <div className="flex-1 overflow-y-auto px-3 py-4 space-y-3">
        {/* SHOP VITALS DASHBOARD (Phase 13) */}
        {messages.length === 1 && (
          <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="p-4 bg-white dark:bg-white/5 border border-gray-100 dark:border-white/10 rounded-2xl shadow-sm mb-6 mx-1"
          >
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-xs font-black text-gray-900 dark:text-white flex items-center gap-2">
                <Sparkles size={14} className="text-[#00E676]" />
                Dukan ki Health (Vitals)
              </h3>
              <span className="px-2 py-0.5 rounded-full bg-[#00E676]/10 text-[#00A846] text-[9px] font-black uppercase tracking-wider">Masha'Allah</span>
            </div>
            
            <div className="grid grid-cols-2 gap-3 mb-3">
              <div className="p-3 bg-gray-50 dark:bg-white/5 rounded-xl border border-gray-100 dark:border-white/5">
                <p className="text-[9px] text-gray-400 font-bold uppercase mb-1">Growth Score</p>
                <div className="flex items-end gap-1">
                  <span className="text-lg font-black text-gray-900 dark:text-white tracking-tighter">{healthScore}%</span>
                  <span className={`text-[9px] font-bold pb-1 underline ${healthScore > 80 ? 'text-[#00C853]' : 'text-orange-500'}`}>
                    {healthScore > 80 ? 'Fit' : 'Checkup'}
                  </span>
                </div>
              </div>
              <div className="p-3 bg-gray-50 dark:bg-white/5 rounded-xl border border-gray-100 dark:border-white/5">
                <p className="text-[9px] text-gray-400 font-bold uppercase mb-1">Liquidity</p>
                <div className="flex items-end gap-1">
                  <span className="text-lg font-black text-gray-900 dark:text-white tracking-tighter">{liquidityStatus}</span>
                </div>
              </div>
            </div>

            <StressMeter score={healthScore} />

            <div className="mt-4 pt-3 border-t border-gray-100/50 dark:border-white/5">
              <p className="text-[9px] text-gray-400 font-bold uppercase mb-2">Munshi's Alerts</p>
              <div className="space-y-1.5">
                {activeAlerts.length > 0 ? activeAlerts.map((alert: string, i: number) => (
                  <div key={i} className="flex items-center gap-2 text-[11px] font-semibold text-gray-600 dark:text-gray-400">
                    <div className={`w-1.5 h-1.5 rounded-full ${i === 0 ? 'bg-red-400 animate-pulse' : 'bg-orange-400'}`} />
                    {alert}
                  </div>
                )) : (
                  <div className="flex items-center gap-2 text-[11px] font-semibold text-[#00A846]">
                    <div className="w-1.5 h-1.5 rounded-full bg-[#00E676]" />
                    Sub fit hai, koi bara masla nahi!
                  </div>
                )}
              </div>
            </div>
          </motion.div>
        )}

        {messages.map((msg) => (
          <motion.div
            key={msg.id}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.22 }}
            className={`flex items-end gap-2 ${msg.isBot ? 'justify-start' : 'justify-end'}`}
          >
            {msg.isBot && (
              <div className="w-8 h-8 rounded-full bg-gradient-to-br from-[#00E676] to-[#00A846] flex items-center justify-center shrink-0 mb-0.5 shadow">
                <UserCog size={14} className="text-white" />
              </div>
            )}
            <div className={`max-w-[84%] rounded-2xl px-4 py-3 relative ${msg.isBot
              ? 'bg-white dark:bg-[#181818] shadow-[0_2px_12px_rgba(0,0,0,0.06)] border border-gray-100 dark:border-white/5 rounded-bl-sm'
              : 'bg-[#00E676] rounded-br-sm shadow-md'}`}
            >
              {msg.isSparkle && (
                <div className="absolute -top-1.5 -right-1.5 w-5 h-5 bg-gradient-to-br from-blue-400 to-indigo-600 rounded-full flex items-center justify-center shadow-sm border border-white dark:border-gray-800">
                  <Sparkles size={10} className="text-white" />
                </div>
              )}
              {msg.isBot 
                ? renderBotMessage(msg.text, msg.isWelcome, allAnomalies, (action) => handleSend(`${action} ke baray mein batao`)) 
                : <p className="text-[14px] font-semibold text-[#0A0A0A]">{msg.text}</p>
              }
              <p className={`text-[10px] mt-1.5 ${msg.isBot ? 'text-gray-400' : 'text-black/50'}`}>
                {new Date(msg.time).toLocaleTimeString('ur-PK', { hour: '2-digit', minute: '2-digit' })}
              </p>
            </div>
          </motion.div>
        ))}

        {/* Typing dots */}
        {isTyping && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex items-end gap-2">
            <div className="w-8 h-8 rounded-full bg-gradient-to-br from-[#00E676] to-[#00A846] flex items-center justify-center shrink-0">
              <UserCog size={14} className="text-white" />
            </div>
            <div className="bg-white dark:bg-[#181818] border border-gray-100 dark:border-white/5 rounded-2xl rounded-bl-sm px-4 py-3 shadow">
              <div className="flex gap-1 items-center h-4">
                {[0, 1, 2].map(i => (
                  <motion.span key={i} className="w-2 h-2 bg-[#00C853] rounded-full"
                    animate={{ y: [0, -5, 0] }}
                    transition={{ duration: 0.6, repeat: Infinity, delay: i * 0.15 }}
                  />
                ))}
              </div>
            </div>
          </motion.div>
        )}

        {/* Quick chips */}
        {messages.length === 1 && !isTyping && (
          <div className="pt-2 px-1">
            <p className="text-[11px] font-bold text-gray-400 uppercase tracking-wider mb-2">Jaldi Poochein</p>
            <div className="flex flex-wrap gap-2">
              {QUICK_CHIPS.map((chip, i) => (
                <button key={i} onClick={() => handleSend(chip)}
                  className="bg-white dark:bg-[#1A1A1A] border border-gray-200 dark:border-white/10 text-gray-700 dark:text-gray-300 text-[13px] font-semibold py-2 px-3.5 rounded-full shadow-sm active:scale-95 transition-transform">
                  {chip}
                </button>
              ))}
            </div>
          </div>
        )}

        <div ref={messagesEndRef} className="h-2" />
      </div>

      {/* ── Input ──────────────────────────────────────────────────────────── */}
      <div className="shrink-0 px-3 py-3 pb-[calc(12px+env(safe-area-inset-bottom,0px))] bg-white dark:bg-[#111] border-t border-gray-100 dark:border-white/5 shadow-[0_-8px_24px_rgba(0,0,0,0.04)]">
        <div className="flex gap-2 items-center">
          <button 
            onClick={startListening}
            className={`w-12 h-12 rounded-2xl flex items-center justify-center active:scale-90 transition-all shadow-md shrink-0 relative overflow-hidden ${
              isListening ? 'bg-red-500 text-white' : 'bg-slate-100 dark:bg-[#1A1A1A] text-gray-400'
            }`}
          >
            {isListening ? (
              <>
                <Mic size={20} className="z-10" />
                <motion.div 
                  initial={{ scale: 1, opacity: 0.5 }}
                  animate={{ scale: 2.2, opacity: 0 }}
                  transition={{ duration: 1, repeat: Infinity }}
                  className="absolute inset-0 bg-red-400 rounded-full"
                />
              </>
            ) : (
              <Mic size={20} />
            )}
          </button>
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSend()}
            placeholder="Kuch bhi poochein…"
            className="flex-1 bg-slate-50 dark:bg-[#1A1A1A] text-gray-900 dark:text-white rounded-2xl py-3 px-4 font-medium text-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#00E676]/30 border border-gray-200 dark:border-white/10 transition-all"
          />
          <button onClick={() => handleSend()} disabled={!input.trim()}
            className="w-12 h-12 rounded-2xl bg-[#00E676] flex items-center justify-center disabled:opacity-40 active:scale-90 transition-all shadow-md shrink-0">
            <Send size={18} className="text-[#0A0A0A] translate-x-[1px]" />
          </button>
        </div>
      </div>

      {/* ── History Panel ───────────────────────────────────────────────────── */}
      <AnimatePresence>
        {showHistory && (
          <HistoryPanel
            sessions={sessions}
            onSelect={handleSelectSession}
            onDelete={handleDeleteSession}
            onClose={() => setShowHistory(false)}
          />
        )}
      </AnimatePresence>
    </div>
  );
};
